name: horse_app
description: An application for managing and tracking horses

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # CSV helper for writing out the database
  csv: ^5.0.0

  # Fonts.
  google_fonts: ^2.1.0

  # Share functions for allowing us to let the user share
  # files or anything else with other services. Is the easiest way
  # to let users save files to their device.
  share_plus: ^3.0.4

  # Form management library, components and dependencies
  reactive_forms: ^11.0.1
  reactive_date_time_picker: ^0.2.2
  reactive_range_slider: ^0.2.0
  image_picker: ^0.8.4+4

  # Widget/framework that allows us to have lists
  # that keep scrolling. We use this on the main pages.
  infinite_scroll_pagination: ^3.1.0

  # Widget that can be expanded to show more content.
  # We use to collapse similar events
  expandable: ^5.0.1

  # Builds the app icon automatically
  flutter_launcher_icons: ^0.9.2

  # Database
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

  # Generates globally unique identifiers for members.
  uuid: ^3.0.6

  # Calendar widget for the events page
  table_calendar: ^3.0.3

  # State management library
  flutter_riverpod: ^1.0.3

  # Store configuration for the app on the user device
  shared_preferences: ^2.0.9

  # Handle notifications for different events
  flutter_local_notifications: ^9.1.5
  flutter_native_timezone: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.0.4
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
