<privacy-policy>
	<h1>Privacy Policy for Stud Manager</h1>
	<p>Last updated: January 30, 2022</p>
	<p>
		This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
		of Your information when You use the Service and tells You about Your privacy rights and how the
		law protects You.
	</p>

	<h1>Interpretation and Definitions</h1>
	<h2>Interpretation</h2>
	<p>
		The words of which the initial letter is capitalized have meanings defined under the following
		conditions. The following definitions shall have the same meaning regardless of whether they
		appear in singular or in plural.
	</p>
	<h2>Definitions</h2>
	<p>For the purposes of this Privacy Policy:</p>
	<ul>
		<li>
			<p>
				<strong>Account</strong> means a unique account created for You to access our Service or parts
				of our Service.
			</p>
		</li>
		<li>
			<p>
				<strong>Application</strong> means the software program 'Stud Manager'
			</p>
		</li>
		<li>
			<p>
				<strong>Device</strong> means any device that can access the Service such as a computer, a cellphone
				or a digital tablet.
			</p>
		</li>
		<li>
			<p>
				<strong>Personal Data</strong> is any information that relates to an identified or identifiable
				individual.
			</p>
		</li>
		<li>
			<p><strong>Service</strong> refers to the Application.</p>
		</li>
		<li>
			<p>
				<strong>Usage Data</strong> refers to data collected automatically, either generated by the use
				of the Service or from the Service infrastructure itself (for example, the duration of a page
				visit).
			</p>
		</li>
		<li>
			<p>
				<strong>You</strong> means the individual accessing or using the Service, or the company, or
				other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
			</p>
		</li>
	</ul>
	<h1>Collecting and Using Your Personal Data</h1>
	<h2>Types of Data Collected</h2>
	<h3>Personal Data</h3>
	<p>
		While using Our Service, We may ask You to provide Us with certain personally identifiable
		information that can be used to contact or identify You. Personally identifiable information may
		include, but is not limited to:
	</p>
	<ul>
		<li>
			<p>Usage Data</p>
		</li>
	</ul>
	<h3>Usage Data</h3>
	<p>Usage Data is collected automatically when using the Service.</p>
	<p>
		Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP
		address), browser type, browser version, the pages of our Service that You visit, the time and
		date of Your visit, the time spent on those pages, unique device identifiers and other
		diagnostic data.
	</p>
	<p>
		When You access the Service by or through a mobile device, We may collect certain information
		automatically, including, but not limited to, the type of mobile device You use, Your mobile
		device unique ID, the IP address of Your mobile device, Your mobile operating system, the type
		of mobile Internet browser You use, unique device identifiers and other diagnostic data.
	</p>
	<p>
		We may also collect information that Your browser sends whenever You visit our Service or when
		You access the Service by or through a mobile device.
	</p>

	<h2>Use of Your Personal Data</h2>
	<p>We may use Personal Data for the following purposes:</p>
	<ul>
		<li>
			<p>
				<strong>To provide and maintain our Service</strong>, including to monitor the usage of our
				Service.
			</p>
		</li>
		<li>
			<p>
				<strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.
				The Personal Data You provide can give You access to different functionalities of the Service
				that are available to You as a registered user.
			</p>
		</li>
		<li>
			<p>
				<strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent
				forms of electronic communication, such as a mobile application's push notifications regarding
				updates or informative communications related to the functionalities, products or contracted
				services, including the security updates, when necessary or reasonable for their implementation.
			</p>
		</li>
		<li>
			<p>
				<strong>For other purposes</strong>: We may use your information for other purposes, such as
				data analysis, identifying usage trends, determining the effectiveness of our promotional
				campaigns and to evaluate and improve our Service, products, services, marketing and your
				experience.
			</p>
		</li>
	</ul>
	<p>We may share your personal information in the following situations:</p>
	<ul>
		<li>
			<strong>With your consent</strong>: We may disclose your personal information for any purpose
			with your consent.
		</li>
	</ul>
	<h2>Retention of your Personal Data</h2>
	<p>
		We will retain your Personal Data only for as long as is necessary for the purposes set out in
		this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply
		with our legal obligations (for example, if we are required to retain your data to comply with
		applicable laws), resolve disputes, and enforce our legal agreements and policies.
	</p>
	<p>
		We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained
		for a shorter period of time, except when this data is used to strengthen the security or to
		improve the functionality of our service, or we are legally obligated to retain this data for
		longer time periods.
	</p>
	<h2>Transfer of your Personal Data</h2>
	<p>
		Your information, including Personal Data, is processed at the Company's operating offices and
		in any other places where the parties involved in the processing are located. It means that this
		information may be transferred to — and maintained on — computers located outside of your state,
		province, country or other governmental jurisdiction where the data protection laws may differ
		than those from your jurisdiction.
	</p>
	<p>
		Your consent to this Privacy Policy followed by your submission of such information represents
		your agreement to that transfer.
	</p>
	<p>
		The Company will take all steps reasonably necessary to ensure that your data is treated
		securely and in accordance with this Privacy Policy and no transfer of your Personal Data will
		take place to an organization or a country unless there are adequate controls in place including
		the security of your data and other personal information.
	</p>
	<h2>Disclosure of your Personal Data</h2>
	<h3>Law enforcement</h3>
	<p>
		Under certain circumstances, the Company may be required to disclose Your Personal Data if
		required to do so by law or in response to valid requests by public authorities (e.g. a court or
		a government agency).
	</p>
	<h3>Other legal requirements</h3>
	<p>
		The Company may disclose your personal data in the good faith belief that such action is
		necessary to:
	</p>
	<ul>
		<li>Comply with a legal obligation</li>
		<li>Protect and defend the rights or property of the Stud Manager</li>
		<li>Prevent or investigate possible wrongdoing in connection with the Stud Manager</li>
		<li>Protect the personal safety of Users of the Stud Manager or the public</li>
		<li>Protect against legal liability</li>
	</ul>

	<h2>Security of Your Personal Data</h2>
	<p>
		The security of Your Personal Data is important to Us, but remember that no method of
		transmission over the Internet, or method of electronic storage is 100% secure. While We strive
		to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its
		absolute security.
	</p>

	<h1>Links to Other Websites</h1>
	<p>
		Our Service may contain links to other websites that are not operated by Us. If You click on a
		third party link, You will be directed to that third party's site. We strongly advise You to
		review the Privacy Policy of every site You visit.
	</p>
	<p>
		We have no control over and assume no responsibility for the content, privacy policies or
		practices of any third party sites or services.
	</p>

	<h1>Changes to this Privacy Policy</h1>
	<p>
		We may update Our Privacy Policy from time to time. We will notify you of any changes by posting
		the new Privacy Policy on this page.
	</p>
	<p>
		You are advised to review this Privacy Policy periodically for any changes. Changes to this
		Privacy Policy are effective when they are posted on this page.
	</p>

	<h1>Contact Us</h1>
	<p>
		If you have any questions about this Privacy Policy, You can contact us: <a
			href="mailto: joelhowse@gmail.com">joelhowse@gmail.com</a
		>
	</p>
</privacy-policy>

<style>
	privacy-policy {
		display: block;
		margin-left: 10rem;
		margin-right: 20rem;
	}

	@media only screen and (max-width: 1000px) {
		privacy-policy {
			margin-left: 0;
			margin-right: 0;
		}
	}
</style>
